#!/bin/bash
allThreads=("0-print_list_integer.py" "1-element_at.py" "2-replace_in_list.py" "3-print_reversed_list_integer.py" "4-new_in_list.py" "5-no_c.py" "6-print_matrix_integer.py" "7-add_tuple.py" "8-multiple_returns.py" "9-max_integer.py" "10-divisible_by_2.py" "11-delete_at.py" "12-switch.py" "13-is_palindrome.c" "lists.h" "100-print_python_list_info.c")

mkdir -p "0x03-python-data_structures"

for t in ${allThreads[@]}; do

    if [[ $t == *".py"* ]]; then
        echo -e "#!/usr/bin/python3\n" > "./0x03-python-data_structures/$t" && chmod +x "./0x03-python-data_structures/$t"
    else
        touch "./0x03-python-data_structures/$t"
    fi

done

echo -e "# ALX Programme Project: 0x03. Python - Data Structures: Lists, Tuples" > "./0x03-python-data_structures/README.md"

cp "0x01-python-if_else_loops_functions/correction" "./0x03-python-data_structures/"

cd /root/alx-higher_level_programming/0x03-python-data_structures