#!/bin/bash
allThreads=("0-script.js" "1-script.js" "2-script.js" "3-script.js" "4-script.js" "5-script.js" "6-script.js" "7-script.js" "8-script.js" "9-script.js" "100-script.js" "101-script.js" "102-script.js" "103-script.js")

mkdir -p "0x15-javascript-web_jquery"

for t in ${allThreads[@]}; do

    if [[ $t == *".py"* ]]; then
        echo -e "#!/usr/bin/python3\n" > "./0x15-javascript-web_jquery/$t" && chmod +x "./0x15-javascript-web_jquery/$t"
    else
        # echo -e "#!/usr/bin/node\n" > "./0x15-javascript-web_jquery/$t"
        touch "./0x15-javascript-web_jquery/$t"
    fi

done

echo -e "# ALX Programme Project: 0x14. JavaScript - Web scraping" > "./0x15-javascript-web_jquery/README.md"

echo -e "#!/bin/bash\ngit add . && git commit -m '0x15. JavaScript - Web jQuery" > "./0x15-javascript-web_jquery/correction" && chmod +x "./0x15-javascript-web_jquery/correction"

cp "../alx-higher_level_programming/0x05-python-exceptions/clean_up_corrections" "./0x15-javascript-web_jquery/"

cd ./0x15-javascript-web_jquery
